### ISSUE TITLE
Index referenced documents

### ISSUE THREAD

**Issue by smilledge** [taterbase/mongoosastic#101]
I'm attempting to index referenced documents. (Without making them sub-documents)

For example;

```
var Author = mongoose.Schema({
    name: { type: String }
}):

var Page = mongoose.Schema({
    title: { type: String },
    author: { type: ObjectId, ref: 'Author' }
});
```

After getting indexed this becomes something like this;

```
"author": {
    _bsontype: "ObjectID",
    id: "SYæSþ\n®àÊF$"
},
```

Is there anyway to index the full referenced object instead of just the ObjectId?

**Comment by taterbase** [comment]
This is a good question and I don't know the answer immediately but we'll look into it.

**Comment by taterbase** [comment]
This issue has been moved to https://github.com/mongoosastic/mongoosastic/issues/8
