### ISSUE TITLE
Index name dependent on field value

### ISSUE THREAD

**Issue by zacharynevin** [taterbase/mongoosastic#104]
I'm not entirely clear on how mongoosastic works. 

Let's say that I want to index data under individual indexes for users. That is, each user has an index with their id. Without mongoosastic, I would just index a new object for user with `id = 1` under `{ index: 'user_1', type: 'object' }`. I know that in mongoosastic I would create the following mapping and can manually index a file like this:

```
ObjectSchema.plugin(mongoosastic, { index: 'user_*', type: 'objects' })

object.index('user_1', 'objects', function(err, res) {
})
```

I guess my real question is: when that object is modified, is it also modified from elasticsearch at the correct index? Is it possible to have objects allocated to the correct index based on their properties? For example, if I have an object that has the field `{ user_id: Schema.Types.ObjectId, ref: 'user' }`, is there a way to tell the river, or write a custom one, that will allocate to the correct index based on `user_id`.

**Comment by taterbase** [comment]
No, not currently. There has been talk of more complex mapping/query/updates like these but for now each schema is its own index. Referenced document storage is on the list of todo.
