### ISSUE TITLE
Docs need example of using .search and iterating through results

### ISSUE THREAD

**Issue by ghost** [taterbase/mongoosastic#105]
I'm looking at some "legacy" code (it was written a few months ago) and it's trying to use the `hits` property of the results:

```
Pharmacy.search(search, function(err, pharmacy) {
  for (var i =0, length = pharmacy.hits.total; i < length; i++) {
    var item = pharmacy.hits.hits[i]._source; // throws an error
    item._id = item.es_id;
    delete item.es_id;
  }
});
```

Are the results returned just a regular array and each item is the same object as the model? Or is it a model with extra properties on it?

**Comment by bobrown101** [comment]
if you make your code: Pharmacy.search(search, {hydrate:true}, function(err, pharmacy) {

it will return an array of mongoose objects in pharmacy.hits, however if you do it the way you have it, it will return the elastic search objects (but in reality pharmacy.hits.hits[i],source is basically representative of the mongoose object).

**Comment by ghost** [comment]
this helped a LOT :+1: thanks! :grin:
