### ISSUE TITLE
Question - cant get mongoosastic to work with bonsai hosting

### ISSUE THREAD

**Issue by bobrown101** [taterbase/mongoosastic#107]
**I can run this code locally (with bonsai url set to the correct url):**

```
  var elasticConnection = url.parse(process.env.BONSAI_URL || 'http://127.0.0.1:9200');
  var postSchema = new Schema({
      title: {type: String, es_indexed:true, index: true},
      slug: {type: String, es_indexed:true},
      link: { type: String, index: true, required: true},
      displayDate: { type: Date, required:true, es_indexed:true},
      author: {type: String, es_indexed:true},
      isoTimeStamp: String,
      content: {type: String, es_indexed:true},
      tags: {type: [String], es_indexed:true, index:true}
  });

  postSchema.plugin(mongoosastic, {host:String(process.env.BONSAI_URL)});
  mongoose.model('postModel', postSchema);
```

and have the documents indexed and returned from this function:

```
  mongoose
    .model('postModel')
    .search({query: searchString}, {hydrate: true}, function(err, results) {
        callback(err, results.hits);
    });
```

HOWEVER, when I run that same code on heroku with mongohq and bonsai ES,
that code does not return anything, leaving results as undefined.

I have been trying to fix this bug for days and am coming here as a last resort. 

This is the project that I am working on: https://github.com/madgloryint/madgalaxy

All of the files involved with ES are located in the lib folder

I don't know if it is something that I am doing wrong, or I am running into a bug, but either way, I would appreciate your help

**Comment by bobrown101** [comment]
The live version of the site is located here: http://madgalaxy.herokuapp.com

The link related to the bug is: http://madgalaxy.herokuapp.com/api/v1/search/?searchString=hello

**Comment by bobrown101** [comment]
I have found out that mongoosastic is indexing the postModels with my local elasticsearch instance instead of the bonsai hosted one - what should I do to force it to use bonsai?

**Comment by bobrown101** [comment]
I have found that mongoosastic will default to the localhost elastic server instead of the bonsai elastic server even with parameters that specify the opposite.

I can configure the standard ES client with these parameters:

```
  var esClient = new elasticsearch.Client({
    host: [
      process.env.BONSAI_URL
    ],
    log: 'trace'
  });
```

and it connects to the correct bonsai server, however, if I configure mongoosastic with these options, it defaults to the localhost server. What am I doing wrong?

**Comment by bobrown101** [comment]
I am still having this issue. Has anyone looked into it and/or had the same problem?

**Comment by bobrown101** [comment]
I have found that on line 119 of lib/mongoosastic.js, I am getting an 'Error: connect ECONNREFUSED'

**Comment by bobrown101** [comment]
I have figured this out and made a pull request to update the readme

**Comment by MaximeHeckel** [comment]
Hi !

How did you manage to solve this issue ? I can't make it work on my own application.
I coded the same thing you did :

```
schema.plugin(mongoosastic,{
  host: [
        process.env.BONSAI_URL
      ],
  log: 'trace'
});
```

But when I launch my mapping this way :

```
Object.createMapping(function(err, mapping){
  if(err){
    console.log('error creating mapping (you can safely ignore this)');
    console.log(err);
  } else {
    console.log('mapping created!');
    console.log(mapping);
  }
})
```

I always get this : 

```
error creating mapping (you can safely ignore this)
{ [Error: unknown error] message: 'unknown error' }
```

Any idea ?

**Comment by bobrown101** [comment]
Here is what I ended up doing:

```
var elasticConnection = url.parse("YOUR_URL_GOES_HERE");
var elasticOptions = {
  host: elasticConnection.hostname,
  port: elasticConnection.port,
  secure: elasticConnection.protocol === 'https:' ? true : false,
  auth: {
    username: elasticConnection.auth.split(':')[0],
    password: elasticConnection.auth.split(':')[1]
  }
};

postSchema.plugin(mongoosastic, {
  host: elasticConnection.hostname,
  auth: elasticConnection.auth,
  port: '',
  //curlDebug: true,
  protocol: elasticConnection.protocol === 'https:' ? 'http' : 'https'
});

```

It has been a while, but I think I remember for some reason that you have to leave the port blank in order for it to work. But the code above is functioning, so its good for me.

**Comment by MaximeHeckel** [comment]
Okay I used your method and it worked ! But only if I fill the port field with the value 443. By default my ES module tried to connect on the 9200 port.

Thank you !
