### ISSUE TITLE
Ability to set typeName dynamically

### ISSUE THREAD

**Issue by davidkaneda** [taterbase/mongoosastic#118]
This is a bit of a specific use, so consider this more of an RFC, but my application allows users to "structure" certain types of entries (ie. custom fields). Generally, in Mongo and ES, I keep all of these documents in one collection/index (entries), as many of the fields are the same (aside from these user-defined fields), and it's much simpler (as I still want people to be able to search against a title across all entries). These differences in structure, though, could lead to Errors on the ES side.

Similar to how I'm handling in Mongo, I'd like to be able to use a single ES index, with different "type" mappings. I'm pretty sure this isn't possible at the moment (though let me know if I'm wrong). I'm wondering if we could somehow support passing a function for the ES document `type`, instead of just defaulting to the model name.

Let me know what you think about this... I'd be willing to take a crack at it if others support the idea-

**Comment by taterbase** [comment]
Sounds interesting but very specific to your use case. I'm open to reviewing a pull request that addresses this but for now it's out of scope.
