### ISSUE TITLE
queue filling and causing Synchronization failure

### ISSUE THREAD

**Issue by staffup-dave** [taterbase/mongoosastic#121]
I have a pretty quick mongodb attempting to use the Schema.synchronize() to another decently powered elasticsearch box. 

The problem was that during sync the queue was being filled and I was getting this error:

```
[Error: EsRejectedExecutionException[rejected execution (queue capacity 200) on org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1@3ba31fab]]
```

I tried using stream.pause() and stream.resume() on the data events emitted by the synchronize stream, but it wasn't working (not sure if a full stream object was passed).

I edited the mongoosastic.js function schema.static.synchronize data events to this:

``` javascript
stream.on('data', function(doc){
      stream.pause()
      counter++;
      doc.save(function(err){
        if (err) {
          stream.resume()
          em.emit('error', err);
          return;
        }
        doc.on('es-indexed', function(err, doc){
          counter--;
          if(err){
            stream.resume()
            em.emit('error', err);
          }else{
            stream.resume()
            em.emit('data', null, doc);
          }
          if (readyToClose && counter === 0)
            close()
        });
      });
    });
```

I've added stream.pause() and stream.resume() events where needed.

My problem with filling the queue disappeared as a result.

If you'd like I can make a schema.static.sychrnozie_throttled function and create a pull request. I've never contributed to anything before - so let me know.

Thanks for the library.

**Comment by tsturzl** [comment]
Right, ElasticSearch doesn't provide durable writing like mongodb, mysql, and other popular databases. Hence the reason a lot of people use it along side another datastore. The problem isn't mongoosastic. I had this problem in the past. We were indexing lots of data into ElasticSearch and we started seeing problems. ElasticSearch has to analyze documents as they come in so it eventually starts dropping documents if its queue fills, it can also timeout your http request in which case you really don't know what happened to your document. You're totally right, the stream should be paused and resumed.

For future reference if you ever run into this issue in production, where elasticsearch cannot index the amount of data you're throwing at it. You can either scale, but eventually you'll need a solution like RabbitMQ-River which allows you to queue documents into RabbitMQ for insertion into ElasticSearch. This will give you a bigger queue.

**Comment by taterbase** [comment]
Hey @staffup-dave I think a throttled version of synchronize would be rad! Feel free to send a PR.

**Comment by jonathanasquier** [comment]
This works well and should maybe be merged?

**Comment by taterbase** [comment]
@jonathanasquier this was an issue, not a PR and thus can't be "merged". If you'd like to make the changes and send a PR please do.

Do note, that a recent update introduced the bulk api. Bulk updates could likely avoid this issue as well.

Keep in mind, we have moved over to https://github.com/mongoosastic/mongoosastic
