### ISSUE TITLE
Support options such as _ttl (time to live)

### ISSUE THREAD

**Issue by ericthelast** [taterbase/mongoosastic#122]
Would it be possible to add support for defining additional mapping options (specifically _ttl)? See http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/mapping-ttl-field.html for reference

**Comment by taterbase** [comment]
Yes, these are already supported. You would just define it as `es_ttl`. See https://github.com/jamescarr/mongoosastic#per-field-options

**Comment by xxidigital** [comment]
I don't know if I should reopen that issue or not, but I can't figure how to use this "es_ttl" inside a mongoose schema to enable it in the real of elasticsearch ? May I ask you a simple example of a mapping using ttl ?

Thanks for the support, this is a great plugin

**Comment by taterbase** [comment]
Oh I didn't realize this was a root level setting. I'll reopen it. To my knowledge this is not currently possible with mongoosastic.

**Comment by taterbase** [comment]
This issue has been moved to https://github.com/mongoosastic/mongoosastic/issues/10
