### ISSUE TITLE
Search Options Not Taken

### ISSUE THREAD

**Issue by staffup-dave** [taterbase/mongoosastic#123]
I wanted to change the default size limit of a search return from 10 to 50. I thought I could just specify 

`{ size: 50 }`

in the options of the schema.static.search function but it wasn't being added to the search body.

I changed how schema.static.search (below) handles options by extending you if statement on the options object. It now adds search params to the search body:

``` javascript
   schema.statics.search = function(query, options, cb){
    var model = this;
    setIndexNameIfUnset(model.modelName);
    if(typeof options != 'object'){
      cb = options;
      options = {};
    }else{
        for(var prop in options){
            if(prop != 'hydrate') {
                query[prop] = options[prop]
            }
        }
    }
    query.index = indexName;

    esClient.search(query, function(err, results, res){
      if(err){
        cb(err);
      }else{
        if (alwaysHydrate || options.hydrate) {
          hydrate(results, model, options.hydrateOptions || defaultHydrateOptions || {}, cb);
        }else{
          cb(null, res);
        }
      }
    });
  };
```

to get { size: 50 } working I simply do:

``` javascript
MySchema.search({query: myQuery}, {size:50}, function (err, docs){
})
```

Let me know if you want me to create a pull-request for this.

Thanks for the plugin!

**Comment by taterbase** [comment]
Hey @staffup-dave, the `.search` function can take a `size` field as well. You just need to perform your query like this:

``` javascript
MySchema.search({query: myQuery, size:50}, function (err, docs){
})
```

Check out the code from our lower level driver [elastical](http://npm.im/elastical) 
https://github.com/ramv/node-elastical/blob/master/lib/client.js#L656-L752
