### ISSUE TITLE
Requesting `Owner` status so I can add more collaborators

### ISSUE THREAD

**Issue by taterbase** [taterbase/mongoosastic#127]
I've emailed James Carr in an effort to request owner status on this repo so I can add some more collaborators to help shoulder the load of this project.

> Hi James,
> 
> I’ve been a collaborator on the Mongoosastic repo for a while now, doing what I can to keep it afloat. There have been some great contributions from the public in recent months and I’d like to start growing the collaborator list and help the repo be more autonomous. Would you be willing to make me an owner so I can add more collaborators now and in the future?
> 
> \- George

**Comment by antoineverger** [comment]
Good idea !!

**Comment by taterbase** [comment]
I've moved all relevant issues to https://github.com/mongoosastic/mongoosastic
