### ISSUE TITLE
{ [Error: ETIMEDOUT] code: 'ETIMEDOUT' }

### ISSUE THREAD

**Issue by varkaha** [taterbase/mongoosastic#129]
A time after I run `model.synchronize();` I get the following messages.

```
{ [Error: ETIMEDOUT] code: 'ETIMEDOUT' }
{ [Error: ETIMEDOUT] code: 'ETIMEDOUT' }
{ [Error: ETIMEDOUT] code: 'ETIMEDOUT' }
{ [Error: ETIMEDOUT] code: 'ETIMEDOUT' }
{ [Error: ETIMEDOUT] code: 'ETIMEDOUT' }
{ [Error: ETIMEDOUT] code: 'ETIMEDOUT' }
{ [Error: ETIMEDOUT] code: 'ETIMEDOUT' }
{ [Error: ETIMEDOUT] code: 'ETIMEDOUT' }
{ [Error: ETIMEDOUT] code: 'ETIMEDOUT' }
{ [Error: ETIMEDOUT] code: 'ETIMEDOUT' }
```

And so on. 

I have 250k+ docs in mongodb, and I want index 2 fields.

I have lastest versions of slasticsearch, mongoosastic, mongoose, and centos6 64bits.

**Comment by TejasCMehta** [comment]
@varkaha  thanks for posting this issue.

Our current project is also facing same problem once we drop mongoDB and try to sync and re-index again with ES.

any help?

**Comment by taterbase** [comment]
`ETIMEDOUT` is a low level error describing a delayed response to a request. I have a feeling this is happening when indexing the documents into Elasticsearch but I'm not positive.

You may be running into an issue that is similar to issue #121 where the queue fills up too quickly and elasticsearch can't index the documents as quickly as you are sending them. Try throttling the sync like they did and let me know if that helps. If so we'll prioritize a throttled sync method.

**Comment by varkaha** [comment]
I do only one "synchronize()" call.

**Comment by taterbase** [comment]
The issue described above is also only doing one `synchronize()` call as well. This can still potentially cause the internal elasticsearch queue to overflow.

**Comment by varkaha** [comment]
Excuse me, I can't understand what I have to do.

**Comment by taterbase** [comment]
@varkaha try editing the `mongoosastic.js` the same way as was done here: https://github.com/jamescarr/mongoosastic/issues/121#issue-44308090

Let me know if that solves the issue.

**Comment by taterbase** [comment]
This issue has been moved to https://github.com/mongoosastic/mongoosastic/issues/11
