### ISSUE TITLE
Round robin requests across multiple indexes

### ISSUE THREAD

**Issue by phillro** [taterbase/mongoosastic#13]
It would be great to be able to provide multiple host parameters and round robin requests across es nodes, especially for indexing. Also might be good to be able to provide different hosts for read & write.

**Comment by jamescarr** [comment]
It seems like the round robin requests would be better done against a load balancer rather than in software. 

Different hosts for read and writes is a good idea though!

**Comment by phillro** [comment]
I kind of think you want the multiple index parameter. Especially if you are on AWS.

I am pretty sure that AWS ELB requests/data from within EC2 will still count as external. This means increased costs and latency and or running one's own load balancer. Its pretty simple to implement, I have it in my elasticsearch driver here:

https://github.com/phillro/node-elasticsearch-client
