### ISSUE TITLE
mapping: property with ObjectId type will neglect other es_ properties

### ISSUE THREAD

**Issue by b96705008** [taterbase/mongoosastic#130]
For example, I have a schema, and it has user property, like:
user: {
        type: Schema.Types.ObjectId,
        ref: 'User',
        es_indexed: true,
        es_type: 'string',
        es_index_analyzer: 'keyword',
        es_cast: function(value){
            if (value._id) {
                return value.id;
            } else {
                return value.toString();
            }
        }
    }

Because I don't want to analyze the user property, and add es_index_analyzer: 'keyword', but I found out that when mongoosastic meet ObjectId type, it will neglect other es_ setting, and that may not meet my need.

**Comment by b96705008** [comment]
I find in mapping-generator.js

for line 55 -> 73, there shouldn't has continue in if
// If it is a objectid make it a string.
    if(value.type === 'objectid'){
      mapping[field].type = 'string';
      continue;
    }

```
//If indexing a number, and no es_type specified, default to double
if (value.type === 'number' && value['es_type'] === undefined) {
  mapping[field].type = 'double';
  continue;
}

// Else, it has a type and we want to map that!
for (var prop in value) {
  // Map to field if it's an Elasticsearch option
  if (prop.indexOf('es_') === 0 && prop !== 'es_indexed') {
    mapping[field][prop.replace(/^es_/, '')] = value[prop];
  }
}
```

**Comment by taterbase** [comment]
This issue has been moved to https://github.com/mongoosastic/mongoosastic/issues/12
