### ISSUE TITLE
Allow Indexing of Virtuals / Composite Fields

### ISSUE THREAD

**Issue by jamescarr** [taterbase/mongoosastic#14]
It could be useful to be able to index virtuals that compute a fixed value based on fields that are stored.

**Comment by jamescarr** [comment]
After some brainstorming, this is going to be a feature that will be turned off by default and enabled by specifying the option index_virtual_fields

**Comment by DallanQ** [comment]
+1 would love to see this.  Another possibility might be: if there is a toElasticSearchJSON() function, call that function to get the json to index. That would give me more control over which fields to index, at the expense of having to write my own function.
