### ISSUE TITLE
Use Batch Operation When Indexing Existing Collection

### ISSUE THREAD

**Issue by jamescarr** [taterbase/mongoosastic#15]
Currently indexing an existing collection can take ages thanks to how slow it is indexing one document at a time. Performance would likely be significantly improved if we index documents in batches of 10 or more at a time.

**Comment by martindale** [comment]
+1 for this feature.

**Comment by gabrielmancini** [comment]
+1

**Comment by brandom** [comment]
@jamescarr I have implemented this and would like to submit a PR.  After reading your contributing section of the README it states that all PRs should be branched from develop but that branch is currently 33 commits ahead and 79 commits behind master.  Should I just submit the PR against master?

**Comment by taterbase** [comment]
This issue has been moved to https://github.com/mongoosastic/mongoosastic/issues/1
