### ISSUE TITLE
Allow Alternative Index Method

### ISSUE THREAD

**Issue by jamescarr** [taterbase/mongoosastic#16]
I have a use case where the business user has a model that is viewed internally and externally. On save it should be indexed, but a specific action causes it to be indexed in a public index for the public website.

**Comment by phillro** [comment]
Yeah, something like Model.index(options, cb) could be interesting.

**Comment by jamescarr** [comment]
Yep, sketching this out atm. So far I'm envisioning an API that allows both indexing as well as indexing to an alternative index. 

``` javascript
Model.index(cb);

Model.index(options, cb);

Model.index(index, options, cb);

Model.index(index, type, options, cb);

```

**Comment by jamescarr** [comment]
Added as of 6c0c4bc
