### ISSUE TITLE
Models don't index if I create the indexMapping manually

### ISSUE THREAD

**Issue by KyleAMathews** [taterbase/mongoosastic#19]
Not sure why. If I create it manually, each time I try to index a model I get the `mapperParsingException` from ElasticSearch which means that the object I sent to be indexed doesn't match the mapping I created previously for the index. But if I just let the index be created automatically by ES then models are indexed correctly.

I'm not sure what's going on here as the mapping that ES reports is identical in either case.

**Comment by jamescarr** [comment]
Added a new test as of 1ded87e to prove that this should now work. I believe this got fixed with a previous issue. 

Feel free to re-open if you still encounter issues!
