### ISSUE TITLE
Possibility to define analysis

### ISSUE THREAD

**Issue by ro-ka** [taterbase/mongoosastic#22]
It would be great to be able to define the [analysis](http://www.elasticsearch.org/guide/reference/index-modules/analysis/) of an index when generated.

Btw: Is the index and the type generated automatically? Or do you have to do that manually?

**Comment by jamescarr** [comment]
Thanks I'll look into this but AFAIK you should be able to define analyzers when manually creating an index.

Indices can be generated automatically or manually. Manual gives you more fine grained control while the automatic doesn't always index types perfectly (basically, you're going to have the best luck with strictly string types).

**Comment by ro-ka** [comment]
So your suggestion is to create an index and a type with the correct names manually, apply analyzers and options and then start mongoosastic and synchronize?

The function createMapping in mongoosastic is for applying the same mapping as defined in the Schema, right? So after creating my index manually I should call that function and start synchromize in the callback?

**Comment by ro-ka** [comment]
Tried out this:

``` javascript
esClient.deleteIndex('profiles', function() {
    esClient.createIndex('profiles', esIndexProfilesOptions, function(error, esIndexProfiles, esResponse) {
        profile.createMapping(function(error, mapping) {
            console.log([error, mapping])
        });
    });
});
```

Delete Index, create new Index with my options (shards, replica and so on) and then called createMapping. Result is the following:

``` javascript
[ [Error: IndexAlreadyExistsException[[profiles] Already exists]],
  { error: 'IndexAlreadyExistsException[[profiles] Already exists]',
    status: 400 } ]
```

First: mongoosastic can not hande it if there is an index present, I can take a look into that and fix it.
Second: Applying these options at index creation time (original subject of ticket) could be a feature to not have to install elastical in addition to mongoosastic for just that. Can take a look in how to implement that.

What do you say?

**Comment by jamescarr** [comment]
I believe you should be able to apply analyzers when you create a mapping through mongoosastic, but like I said I have not verified it. :)

I'll write a test case for it when I get to it this week. If it passes, it goes into the documentation. If it doesn't, new feature. :)

**Comment by ro-ka** [comment]
Sent a pull request for the handle existing index issue.  :)

To the subject: There currently is no way to pass the settings array to the createMapping function. There should be an extra (optional) parameter to pass the settings.

But there occur some problems then:
- The analyzers and other options of the index can only be given to the index at creation time. That is not always the case when calling current `createMapping`.
- The Mapping can always be updated but changing a type from string to integer will result in an error.

So two things I would suggest:
- The function `createMapping` should be named `updateMapping` and update the mapping of an existing index. Maybe it could even create a new index with the mapping if the index is not present.
- There should be a function `createIndex` which creates the index with optional settings as an object (number of shards, number of replicas, analyzers,...) to pass in. This will then create the index with the mapping from the Schema. Maybe it could delete the old index already existing.

**Comment by DallanQ** [comment]
Just to be clear, if I want to create an index with a custom analyzer, I first call elastical's indexExists to see if the index exists.  If it does not, I call elastical's createIndex function and pass in my "settings" object, then I call mongoosastic's createMapping function.  Is this correct?

**Comment by ro-ka** [comment]
That's how I do it atm, yes.

**Comment by itamarwe** [comment]
Would be great if any of you could give a more concrete example of how to define the analysis. Thanks.

**Comment by saurabhghewari** [comment]
Please provide me with the detailed example how to create custom mappings?

**Comment by ro-ka** [comment]
I'm sorry, but I don't use mongoosastic anymore. That's why I don't have any examples left.

**Comment by saurabhghewari** [comment]
Ok, but atleast help me in explaining what exactly the Dallan Q sir has commented?

**Comment by ro-ka** [comment]
You need an index, so he is checking if an index exists before he starts mongoosastic. Does this help?
