### ISSUE TITLE
Easiest way to index existing data?

### ISSUE THREAD

**Issue by KyleAMathews** [taterbase/mongoosastic#3]
Really excited to have come across this module earlier. Looking forward to adding it to a number of projects which need full-text search.

But that raises the question of how to index all my existing models inside MongoDB. Reading through the code I didn't see anything built explicitly to do that. Would the easiest thing to do is to just load each model and loop through  each and resave to trigger their being indexed in ElasticSearch?

**Comment by jamescarr** [comment]
I have a feature branch I haven't pushed out yet that adds a synchronize method to re-index existing models. 

For now, just loading them all and re-saving them would probably be the best way to accomplish the goal. I'll close this issue once I merge the feature branch and perform a new release

**Comment by jamescarr** [comment]
Added in 81f17c128d5e00ae6b61bfb3be8b0f2ba427c790 at [line 45](https://github.com/jamescarr/mongoosastic/commit/81f17c128d5e00ae6b61bfb3be8b0f2ba427c790#L0R45)

**Comment by KyleAMathews** [comment]
I tried testing the synchronize method tonight w/o much success. It indexes 5 models then quits. It throws the following errors:

```

(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace: 
    at Socket.<anonymous> (events.js:139:15)
    at Socket.once (events.js:160:8)
    at Socket.setTimeout (net.js:143:12)
    at ClientRequest.setTimeout (http.js:1388:17)
    at ClientRequest.<anonymous> (http.js:1400:10)
    at ClientRequest.g (events.js:156:14)
    at ClientRequest.emit (events.js:88:20)
    at Array.10 (http.js:1346:9)
    at EventEmitter._tickCallback (node.js:190:38)
```

**Comment by jamescarr** [comment]
I'll modify the test for it to create an existing collection with 10 models and see what happens. Looks like there's an EventEmitter memory leak somewhere.

**Comment by jamescarr** [comment]
Discovered this was due to fetching the mapping for the indexing and creating it if it doesn't exist. Magically. There's an EventEmitter leak but I've decided that creating the mapping magically was ill advised. 

I'm going to break out a new method to createMapping and let the end user decide to create it.

**Comment by jamescarr** [comment]
New synchronize API, see readme.md @ 947bf7c640e252dfa30800a0cabb5dc61bb7bfed
