### ISSUE TITLE
hydrate should take mongoose options

### ISSUE THREAD

**Issue by phillro** [taterbase/mongoosastic#30]
Allow hydrateOptions to be set. Should include options such as lean, sort, populate, etc.

**Comment by jamescarr** [comment]
Hmmm... can you expand?

By lean do you mean do a "shallow" hydration and don't populate nested objects?

**Comment by phillro** [comment]
No. lean is an option available in mongoose v3 that instructs mongoose to not attach all the mongoose handlers to docs. Its useful for improving the performance of read-only queries.

Other things that could be passed in include sort, etc.
