### ISSUE TITLE
mapping generator using non es types

### ISSUE THREAD

**Issue by phillro** [taterbase/mongoosastic#34]
The mapping generator is attempting to set Mongoose fields of type number to an es type of number. This generates a mapping error. I think this should set it to one of the core types.

**Comment by niftylettuce** [comment]
any solution yet?

**Comment by niftylettuce** [comment]
If you add after line 49 of `mapping-generator.js`:

``` js
if (value.type === 'number') {
  mapping[field].type = 'float'
}
```

However, this sets all Number types to floats, and some might be integers, so we really need to look into a better solution.
