### ISSUE TITLE
Dies when es_indexed: true is set on more than 6 fields

### ISSUE THREAD

**Issue by jamescarr** [taterbase/mongoosastic#42]
A user has reported that mongoosastic dies when trying to index documents with es_indexed: true set on 6 fields. 

From some simple logging, I can tell you the following from some simple logging...the doc.save() in synchronize() in mongoosastic.js (~line 80ish) is what seems to throw the error.  the log(sync 6) never gets hit:

``` javascript

    stream.on('data', function(doc){
      var self = this;
      log.sub('Mongoosastic').line('synchronize 4');
      self.pause();
      log.sub('Mongoosastic').line('synchronize 5');
      doc.save(function(){
        log.sub('Mongoosastic').line('synchronize 6 in doc.save');



```

**Comment by taterbase** [comment]
I can't seem to replicate this issue. Is this a special instance? I tried when just saving a model and also when synchronizing existing models.

**Comment by jamescarr** [comment]
The guys at @storify ran into this. I'm not sure it is still a problem anymore though.

**Comment by taterbase** [comment]
Since this issue is so old and we don't have any information on how to recreate (@storify please let me know if this is not the case) I'm going to go ahead and close this for the time being.
