### ISSUE TITLE
Stops indexing new posts after restarting server

### ISSUE THREAD

**Issue by KyleAMathews** [taterbase/mongoosastic#5]
Search still works but new posts and old posts that I save aren't indexed any longer.

**Comment by jamescarr** [comment]
After restarting elasticsearch server or an app server using mongoosastic?

**Comment by KyleAMathews** [comment]
An app server using Mongoosastic.

**Comment by jamescarr** [comment]
I found the reason for this while working on the feature to index an existing collection. Basically I was only determining the index and type names on save if they weren't provided.

**Comment by jamescarr** [comment]
Can you check to see if this is fixed in the develop branch? I'm currently formulating a way to test this but it will require starting and stopping a remote process.

**Comment by KyleAMathews** [comment]
Cloned and switched to the develop branch and nothing changed. Neither editing an existing post or adding a new post affected the index.

**Comment by jamescarr** [comment]
I've added an example blog app under examples. It's ugly, but it works. I don't seem to be able to reproduce the problem anymore in develop. 

I'm going to keep the issue open in case you can reproduce.

**Comment by KyleAMathews** [comment]
Woot! Upgraded to your latest release and things are working really well it seems. Can restart server with abandon and the synchronize method is working great w/ no duplications as it had in the past.

**Comment by jamescarr** [comment]
Awesome!
