### ISSUE TITLE
synchronize failing

### ISSUE THREAD

**Issue by ttezel** [taterbase/mongoosastic#50]
I have an existing dataset in mongo which I have tried to index into elasticsearch without success. After running `.synchronize()`, I get 9 'data' events, and the stream never emits 'close' or 'error'. So only 9 documents seem to be getting indexed (I have much more than 9 in my DB). Here's the code:

``` javascript
collection.schema.plugin(mongoosastic)

var indexModel = mongoose.model(collection.modelName, collection.schema, collection.collectionName)

var syncStream = indexModel.synchronize()
var synced = 0

syncStream.on('data', function (err, doc) {
    if (err) throw err

    synced++

    console.log('indexed', synced)
})

syncStream.on('close', function () {
    var numCollections = COLLECTIONS.length

    console.log('finished indexing %s/%s collections', synced, numCollections)
})

syncStream.on('error', function (err) {
    throw err
})
```

**Comment by taterbase** [comment]
I know you filed this issue quite a while ago, are you still experiencing the same problem? If so I'll need some more info such as:
- The schema you are using
- How many existing docs you have

**Comment by ttezel** [comment]
hey @taterbase  actually ended up implementing the indexing using mongoose directly

**Comment by taterbase** [comment]
Ok, good to know. I will close the issue for now. Thanks!
