### ISSUE TITLE
geo_point mapping using an array doesn't work

### ISSUE THREAD

**Issue by reezer** [taterbase/mongoosastic#53]
As described [here](http://www.elasticsearch.org/guide/reference/mapping/geo-point-type.html) lat, long can be provided as an array. However it doesn't appear to work:

```
SomesSchema = mongoose.Schema({
  ll: {
    type: [Number],
    es_type: 'geo_point'
  }
});
```

This will map `ll` to long.

**Comment by taterbase** [comment]
Hi @reezer,

I believe the problem you are running into is not calling `createMapping` on model before saving documents. Something like this should work:

``` javascript
SomesSchema = mongoose.Schema({
  ll: {
    type: [Number],
    es_type: 'geo_point'
  }
});

var Somes = mongoose.model('somes', SomesSchema);

Somes.createMapping(function(err, mapping){
  //your mapping should now be created with you geo_point correctly
});
```

Please let me know if this helps.
