### ISSUE TITLE
Highlight not working.

### ISSUE THREAD

**Issue by KyleAMathews** [taterbase/mongoosastic#6]
I'm working on integrating Mongoosastic into an app of mine. I want to use the highlighted search functionality provided by ElasticSearch. That wasn't working at first as the mapResults() function only pulls off the _source dictionary from the ElasticSearch results set ignoring the highlight dictionary.

So two options to solve this. One, have a special "raw" mode that just returns exactly what Elastical returns. Two, make mapResults raw -- I don't see any compelling reason to not just return everything and just skip the mapping. Other than a small increase in the amount of data we'd be sending back to the client.

**Comment by KyleAMathews** [comment]
I can create a pull request on whatever you decide. Either is fine with me though I'd prefer the simplicity of just returning everything.

**Comment by jamescarr** [comment]
Yeah let's go ahead and return everything... I'd like to continue using the map that hydrates documents but it'd be more useful to give the user the full data, especially since they'd need it for paging. 

Can you issue a pull request against the develop branch?

**Comment by jamescarr** [comment]
Merged into develop, releasing with 0.6 release.
