### ISSUE TITLE
river mongo as a option

### ISSUE THREAD

**Issue by gabrielmancini** [taterbase/mongoosastic#61]
Hi James,

   I learned about your project and i feel very excited about it,
   And had thinking about use this guy 

https://github.com/richardwilly98/elasticsearch-river-mongodb 

to make the search and keep the updated data in my app.
   I propouse write some option like useRiver:true to  make something like that 

```
if (!useRiver) {
  schema.post('remove', function(){
    var model = this;
    setIndexNameIfUnset(model.constructor.modelName);
    deleteByMongoId(esClient, model, indexName, typeName, 3);
  });


  schema.post('save', function(){
    var model = this;
    model.index(function(err, res){
      model.emit('es-indexed', err, res);
    });
  });
}
```

and some how put this document on es 

```
http://localhost:9200/_river/mongodb/_meta' -d '{
    "type": "mongodb",
    "mongodb": {
        "db": "noobjs_dev",
        "collection": "posts",
        "gridfs": false
    },
    "index": {
        "name": "posts",
        "type": "post"
    }
}
```

what u think?
sorry about my english

**Comment by taterbase** [comment]
Hi Gabriel,

Thanks for you input! I apologize if I did not understand your suggestion properly but it seems like you are asking that Mongoosastic be able to index documents automatically when they are saved to MongoDB? If so, that is already implemented! Mongoosastic uses Mongoose's `post('save')` to index your documents as you save and change them as well as `post('remove')` to remove an index.

Does that answer your question?

**Comment by gabrielmancini** [comment]
Hi George,

   I Want use river http://www.elasticsearch.org/guide/reference/river/, this feature has capacity to working well with clustering node and we can streaming the search http://www.elasticsearch.org/2010/09/28/the_river/, to use river on mongo we can use this plugin https://github.com/richardwilly98/elasticsearch-river-mongodb, so my suggestion is create an option.useRiver = true and wrap the eventListener of mongoose. And Create the river esClient.putRiver.

sorry my english again ;-)

**Comment by taterbase** [comment]
Ok, I understand. Thanks for bringing this to our attention. I think this should definitely be an option :)

**Comment by gabrielmancini** [comment]
Hi George,

The travis-ci broken because you need follow the instructions on Readme.md
Start mongodb with replicaset, and install river mongo plugin on es.
on my env all work well, all tests pass.

[]s

**Comment by taterbase** [comment]
Whoah, thanks Gabriel! I won't have time to review this until this weekend but I will then. Also thanks for doing a test :)

**Comment by gabrielmancini** [comment]
Hi George,

  i change the .travis a little bit to make work useRiver tests, can you review my pull request? i need this in my project.

cheers

**Comment by taterbase** [comment]
Gabriel,

This looks awesome. Thank you for the awesome pull request :)

**Comment by gabrielmancini** [comment]
Hi George,

   Do you have a time preview to next release? i have some guys in my team who need this feature to continue the develop of the project who i m working.
   And its always a pleasure contribute with a so cool project :-)

cheers

**Comment by taterbase** [comment]
Hi Gabriel,

Sorry about the delay. I have never set up replica sets before so I am struggling to get that set up and working for tests (I want to make sure the tests pass locally as well as on Travis). Work has been a bit busy and I haven't had a ton of time to play with it. I'll continue to try and get this merged in as soon as possible.

**Comment by gabrielmancini** [comment]
Hi George

    Dude I'm sorry if I pushed you, it was not my intention, if you need help setting up replica set I'm available, contact the gtalk gabriel.mancini@gmail.com

**Comment by taterbase** [comment]
Oh no, you haven't don't worry :). It's just been a busy week.

**Comment by taterbase** [comment]
@gabrielmancini are replica sets absolutely necessary to use the mongodb river functionality?

**Comment by gabrielmancini** [comment]
Hi George

   How are you man? I hope is every thing its ok.
   is in the wiki doc of plugin mongo-es-rive https://github.com/richardwilly98/elasticsearch-river-mongodb/wiki#design ..."The current implementation monitors oplog collection from the local database. Make sure to enable replica set"...

**Comment by deedubs** [comment]
Would love to see this landed. We could use a Vagrant setup for testing the replicaSet stuff locally in a repeatable straightforward manner.

**Comment by gabrielmancini** [comment]
to test? good idea

On Wed, Oct 23, 2013 at 1:22 PM, Dan Williams notifications@github.comwrote:

> Would love to see this landed. We could use a Vagrant setup for testing
> the replicaSet stuff locally in a repeatable straightforward manner.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jamescarr/mongoosastic/issues/61#issuecomment-26914244
> .

## 

Gabriel Mancini de Campos
Arquiteto de Soluções

+55 (11) 9449-1706
gabriel.mancini@gmail.com
São Paulo - SP - Brasil

**Comment by taterbase** [comment]
Rivers in Elasticsearch are deprecated https://www.linkedin.com/groups/Official-guide-writing-ElasticSearch-rivers-3393294.S.268274223
