### ISSUE TITLE
Searching for nested models

### ISSUE THREAD

**Issue by itamarwe** [taterbase/mongoosastic#67]
I would like to be able to search for nested models. For example, in this schema:

``` javascript
var Comment = new Schema({
    title: String
  , body: String
  , author: String
})


var User = new Schema({
    name: {type:String, es_indexed:true}
  , email: String
  , city: String
  , comments: {type:[Comment], es_indexed:true}
})
```

I would like to search for comments that match a certain text, for users in a certain city. I would like the query to return only the comments that match the query.

My questions are:
1. Is there a way to store the comments in a separate index, where the user is the parent? (while still using mongoosastic and not a custom solution)
2. Is there another way to search for the comments, without the need to filter the results after they are returned?

**Comment by taterbase** [comment]
> Is there a way to store the comments in a separate index, where the user is the parent? (while still using mongoosastic and not a custom solution)

No not at this time. You can try making comments their own collection and use the `ref` property on User for comments.

> Is there another way to search for the comments, without the need to filter the results after they are returned?

When you say filter the results do you mean in the application code? If so yes, you can make use of Elasticsearch's filter attribute of the query, potentially even the [regexp filter](http://www.elasticsearch.org/guide/reference/query-dsl/regexp-filter/). Filters in Elasticsearch give you more control over your results and are also cacheable.

**Comment by itamarwe** [comment]
> No not at this time. You can try making comments their own collection and use the ref property on User for comments.

That's what I also had in mind. Is there a way to map the user as the parent of the comments, in order to create search queries on both the user and the comment?

**Comment by taterbase** [comment]
> Is there a way to map the user as the parent of the comments, in order to create search queries on both the user and the comment?

I believe you can set the `es_parent` field like so:

``` javascript
var Comment = new Schema({
    title: String
  , body: String
  , author: String
  , es_parent: 'users'
})
```

But I am not positive. If that is not the case I think this would be a good feature to have and we can work to include it.

**Comment by itamarwe** [comment]
I think it will be more complicated then this, since you need to specify the actual parent for each entry.
+1 for adding this functionality.

**Comment by gabrielmancini** [comment]
+1

**Comment by vladexologija** [comment]
+1

**Comment by taterbase** [comment]
This issue has been moved to https://github.com/mongoosastic/mongoosastic/issues/4
