### ISSUE TITLE
Indexing only certain documents in a collection

### ISSUE THREAD

**Issue by jeffwhelpley** [taterbase/mongoosastic#68]
I have several Mongo collections where I store multiple types (ex. collection posts with types review, story, question, etc.). Is there a way to only index to ES one type from my Mongo collection?  In other words, only index to ES if type = review with collection posts?

**Comment by deedubs** [comment]
You should be able to do this now with https://github.com/jamescarr/mongoosastic/pull/72#issuecomment-29685171 landed

**Comment by taterbase** [comment]
Indeed!
