### ISSUE TITLE
Not indexing nested fields

### ISSUE THREAD

**Issue by lagoasoft-lucasschmidt** [taterbase/mongoosastic#69]
Hey,
if I dont use es_indexed = true in my schema, everything works, all fields are indexed.

If I use them, all fields that are nested, like below, do not work.

{
object: {
     field1: {type: String, es_indexed: true}
}

"object" field is not indexed, and its not available as source as well.

Do you guys have experienced this as well? Thanks.

**Comment by taterbase** [comment]
Could you post the schema in question? I believe you are trying to index a sub-object which as far as I know is not currently supported.

**Comment by lagoasoft-lucasschmidt** [comment]
Correct, I believe its named sub-object. Its based on the Mapping options on the README of this repo.

  // Object type 
  object: {
    field1: {type: String},
    field2: {type: String}
  },

My partial schema

{
      active: {
        type: Boolean,
        required: true,
        "default": false
      },
      email: {
        type: String,
        required: true,
        unique: true
      },
      address: {
        district: {
          type: String,
          required: true
        },
        street: {
          type: String,
          required: true
        },
        zipcode: {
          type: String,
          required: true
        },
        city: {
          type: String,
          required: true
        },
        state: {
          type: String,
          required: true
        },
        country: {
          type: String,
          required: true
        }
      }
}
