### ISSUE TITLE
mongoose 3.8

### ISSUE THREAD

**Issue by pgherveou** [taterbase/mongoosastic#73]
Hello @jamescarr did you have chance to look at last mongoose stable release 3.8.x
also maybe we should add mongoose as a peerdependencies in package.json
instead of a hard dependency, what do you think?

**Comment by ranadeep47** [comment]
Also elasticsearch recently rolled out its own js [client](https://github.com/elasticsearch/elasticsearch-js) , guess we should move to it from elastical

**Comment by taterbase** [comment]
@aardee47 pretty neat, did not know that. No plans at this time to switch over but it's a good idea.
