### ISSUE TITLE
error with object id 

### ISSUE THREAD

**Issue by marcguevremont** [taterbase/mongoosastic#77]
[Error: MapperParsingException[failed to parse [_user]]; nested: ElasticSearchIllegalArgumentException[unknown property [_bsontype]]; ]

**Comment by taterbase** [comment]
Hi!

This doesn't provide me with enough information to debug or help. Can you describe the issue you are seeing in more depth? I will close this issue until then.

**Comment by marcguevremont** [comment]
I got ths error because I refer to an other Schema in my collection. The
type is ObjectId(). This is a serialization error. I downgraded to v.0.11
and it is working

thank you

**Comment by aschmid** [comment]
this was fixed here https://github.com/jamescarr/mongoosastic/issues/17
why was this fix dropped? or how would i query for a referenced object in a query if its not a string?

**Comment by aschmid** [comment]
to clarify i am using the model-path-tree module. which adds a parent property to the schema like here:
https://github.com/swayf/mongoose-path-tree/blob/master/lib/tree.js#L33

now im not sure if that module does something wrong or if its mogoosastic not covering this case.
the easiest fix for me right now is to add this if clause in the serialize.js of mongoosastic like here:

function serialize(model, mapping) {

  if (mapping.type === 'string' && typeof(model) !== 'string') {
    model = model.toString();
  }
....

but im not sure if this is the optimal solution for this case.
whats happening is that the parent property is an object but mapping.type states its a string.

here: https://github.com/jamescarr/mongoosastic/blob/master/lib/mapping-generator.js#L55
while the mapping returns a {type: string} for ObjectId the serialize function does not really take care of indexing a string but sends an object to elasticsearch which causes this issue.

this looks like a bug to me.

**Comment by taterbase** [comment]
I'm just digging back into this repo, going to reopen for now but haven't fully evaluated what is going on here.

**Comment by aschmid** [comment]
@taterbase i fixed this issue in my pull request you already merged into master! thx
https://github.com/jamescarr/mongoosastic/pull/112

**Comment by taterbase** [comment]
sweet!
