### ISSUE TITLE
Elastic Search Hyphen issue with term filter

### ISSUE THREAD

**Issue by gabrielmancini** [taterbase/mongoosastic#83]
Hi Guys,

   I Had a problem with hiphens in tag names, something like this: http://stackoverflow.com/questions/16698517/index-fields-with-hyphens-in-elasticsearch 
  there is a way to customize the mapping or the analyzer of the index using mongoosastic? 

thanks all

**Comment by taterbase** [comment]
This issue has been moved to https://github.com/mongoosastic/mongoosastic/issues/6
