### ISSUE TITLE
Synchronize and Encrypted Data

### ISSUE THREAD

**Issue by stongo** [taterbase/mongoosastic#84]
Don't really know if this is a bug but thought I would share and maybe you could suggest a solution. I have several models that encrypt user data on a 'save' pre hook but because `schema.statics.synchronize()` calls `document.save()` it fires the hook and ends up double encrypting my data. The current model and controllers code assumed that documents would be instantiated or updated with unencrypted data, so it will be a lot of refactoring to remove it from pre save hook.

**Comment by b96705008** [comment]
I have a problem that demonstrate "have no method index" for a doc when I call the sync.. Method..

**Comment by b96705008** [comment]
Sorry it's my fault, I override the methods by doing -> UserSchema.methods = {...}...

**Comment by taterbase** [comment]
Synchronize just fires off saves to make use of the mongoosastic hook. It's likely not the best method. In the future I would check to see if the data has changed before encrypting

http://mongoosejs.com/docs/api.html#document_Document-isModified
