### ISSUE TITLE
Use Completion Suggester or Autocomplete in Mongoosastic

### ISSUE THREAD

**Issue by b96705008** [taterbase/mongoosastic#85]
I wanna do the autocomplete when searching, but I don't know how to do this by using Mongoosastic. Elasticsearch has Completion Suggester that can do that, but the mapping setting is more complicated than the Mongoosastic's mapping api can do, so I just wanna solve this problem. Another mongoose plugin called "elmongo" has Autocomplete function that can be used easily, can Mongoosastic do that too?

**Comment by taterbase** [comment]
Autocomplete-like functionality depends on your mapping and query. Mongoosastic can be used for autocomplete, it just requires you to create the right query when calling `search`. Also [highlighting](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-request-highlighting.html) may have some good tools for you.
