### ISSUE TITLE
[Question] how to sync arrays?

### ISSUE THREAD

**Issue by felixsanz** [taterbase/mongoosastic#89]
Hi there, im having troubles syncing arrays.

This is my actual mongoose schema:

```
var PostSchema = mongoose.Schema({
  name: { type: String, es_indexed: true },
  tags: { type: [String], es_indexed: true },
});
```

Which produce in mongodb a field like: `"tags" : [  "tag1",  "tag2",  "tag3" ]`

The problem is while using mongoosastic to sync elasticsearch with mongodb, im getting this error:

> [Error: MapperParsingException[object mapping [tags] trying to
> serialize a value with no field associated with it, current value
> [tag1]]]

The code i use to sync it is this:

```
PostSchema.plugin(mongoosastic);

var Post = mongoose.model('Post', PostSchema);
var stream = Post.synchronize();

stream.on('error', function(err){
  console.log(err);
});
```

Can someone give me a hand please?

**Comment by ishakya** [comment]
I am also having the problem with synchronizing array data. @felixsanz did u find any solution?

**Comment by felixsanz** [comment]
@ishakya I end up using this:

```
tags: { type: Array, es_indexed: true, es_type: 'string' },
```

Dunno if it helps

**Comment by reza-rahman-rx** [comment]
@felixsanz, You made my day, thanks a lot.
