### ISSUE TITLE
Custom raw mapping

### ISSUE THREAD

**Issue by xizhao** [taterbase/mongoosastic#94]
Can we allow the user to configure custom mappings on some fields?  For instance, I am using a mixed field type that I'd like to index with multiple nested modules.  I'd like to be able to specify my own paths/mappings in here.

**Comment by aschmid** [comment]
yes it would be very useful to pass a function to the model schema that does a custom serialization of that field before indexing it in elasticsearch.

**Comment by taterbase** [comment]
https://github.com/jamescarr/mongoosastic/pull/120 fixed this
