### ISSUE TITLE
two issues - deletion and condition of index

### ISSUE THREAD

**Issue by tmkctm** [taterbase/mongoosastic#95]
I went through all the code and the issues in this project but i still haven't found my answer.
First, I did as the readme.md says and i do get my document indexes and the search is working BUT when i delete a document using mongoose, es still returns it in results. Am I to delete it by myself? How?

Secondly, I saw something about parameter in synchronize which allows to sync sub set of a collection, but im afraid i could find anything about how to use it. Once i do the plugin, i wish for the index on a certain document to happen only a field is true. Is that possible?
Thanks for the help

**Comment by tmkctm** [comment]
Ok, I found the bug, but I have no idea how to fix it.
Here is my mongoose code:
Models[type].findOne(query, function(err, item){
        if (err) callback('at removeItem: Failed to remove an item of type '+type+', query: '+JSON.stringify(query)+' ('+err+')', null);
        else item.remove(function(err, data) {
            callback(null, item);
        });
    });

This works... but what I had before which didnt work was this:
Models[type].findOneAndRemove(query, function(err, item){
        if (err) callback('at removeItem: Failed to remove an item of type '+type+', query: '+JSON.stringify(query)+' ('+err+')', null);
        else callback(null, item);
    });
it seems the schema.post doesn't work for modal methods in mongoose ??

**Comment by taterbase** [comment]
Correct, mongoosastic only attaches schema level hooks. Instance level actions do not trigger these.
