### ISSUE TITLE
Question: Pagination

### ISSUE THREAD

**Issue by umuplus** [taterbase/mongoosastic#98]
Hello everyone,

According to official elasticsearch node.js library's online documentation, pagination should be applied like that:

{from: 0, size: 10, body: {query: {match: {_all: "test"}}}}

http://www.elasticsearch.org/guide/en/elasticsearch/client/javascript-api/current/api-reference.html

But same expression doesn't work within mongoosastic's search method. Is there any other way to implement pagination?

**Comment by romuloctba** [comment]
This is a nice question, but "Commit has since been removed from the repository and is no longer available. "

**Comment by antoineverger** [comment]
Hi @umuplus ,

I'm using Mongoosastic the way you described for pagination (except that the keyword body is not needed) : {from: 0, size: 10, query: {match: {_all: "test"}}} should be sufficient.

If not, you can use Sense to test your queries (or even CURL).

You can also debug your queries using the option curlDebug: true when you set up the plugin (check that here : https://github.com/jamescarr/mongoosastic#modelpluginmongoosastic-options

**Comment by taterbase** [comment]
:+1: @antoineverger
